name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make libft

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install -y libbsd-dev libncurses-dev
    - name: Install and build libft-unit-test
      run: | 
        git clone https://github.com/alelievr/libft-unit-test.git libft-unit-test && \
        make libft-unit-test
    - name: Run Tests
      run: libft-unit-test/run_test
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: libft-unit-test/result.log