name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: install dependencies
      run: sudo apt-get install -y gcc libbsd-dev libncurses-dev

    - name: clone test repo
      run: git clone https://github.com/alelievr/libft-unit-test.git /tmp/libft-unit-test && sed -i "s|^\(LIBFTDIR[ \t]*=[ \t]*\)\.\./libft|\1$(pwd)|" /tmp/libft-unit-test/Makefile && cd /tmp/libft-unit-test

    - name: run tests
      run: cd /tmp/libft-unit-test && make && ./run_test

    - name: upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: /tmp/libft-unit-test/results.log